#language:pt

Funcionalidade: Geração de Pedidos

@pedidos
Esquema do Cenário: Gerar Pedidos

Dado que eu realize uma cotação com  <cliente>, <revenda>, <nomecliente>, <tipooperacao>, <condpagamento>, <topico>, <tipovenda>, <condiFrete>, <taxainclusa>, <material>, <imprime_nfe>, <nro_nr>, <nro_Item>, <descdopedido> 
Quando eu realizar as aprovações
Entao o pedido será gerado



Exemplos:
| cliente       | revenda   | nomecliente                                                       					| tipooperacao										|condpagamento| topico  |       tipovenda  		| condiFrete|taxainclusa|       material            |   imprime_nfe |   nro_nr      | nro_Item  |    descdopedido 	    | 
|   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0036"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80677I37100 I SN"                 |"N"           |""             |  "1"      |  "CT0036 - Gerar pedido de venda estabelecimento = 5 com Tipo de Operação = 1-VENDAS e Venda para uso e"|
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[64] SIMPLES REMESSA (COM IMPOSTOS)               |"28"         |"CT0037"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "MSEDD2647"             |"N"           |""             |  "1"      |  "CT0037 - Gerar pedido de venda estabelecimento = 5 com Tipo de Operação = 64-SIMPLES REMESSA (COM"    |  
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT0038"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "MSEDD2647"             |"N"           |""             |  "1"      |  "CT0038 - Gerar pedido de venda estabelecimento = 5 com Tipo de Operação = 1-VENDAS e Venda para"      |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT00390103"|"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "AZURE"                 |"N"           |""             |  "1"      |  "CT0039 - Gerar pedido de venda estabelecimento = 5 com Tipo de Operação = 1-VENDAS e SERVIÇO 01.07,"  |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT00390106"|"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "INF-365-DIR"           |"N"           |""             |  "1"      |  "CT0039 - Gerar pedido de venda estabelecimento = 5 com Tipo de Operação = 1-VENDAS e SERVIÇO 01.07,"  |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT00390107"|"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "EXCHNGSTAND(1Y)"       |"N"           |""             |  "1"      |  "CT0039 - Gerar pedido de venda estabelecimento = 5 com Tipo de Operação = 1-VENDAS e SERVIÇO 01.07,"  |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT00391401"|"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "5WS0G54138"            |"N"           |""             |  "1"      |  "CT0039 - Gerar pedido de venda estabelecimento = 5 com Tipo de Operação = 1-VENDAS e SERVIÇO 01.07,"  |
# |   "66568"     |""         |"[66568] MG - BELO HORIZONTE - ASM INFORMÁTICA CARTUCHOS E TONER LTDA"                 |"[1] VENDAS"                                       |"28"         |"CT0041"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "62251"                 |"N"           |""             |  "1"      |  "CT0041 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda para"     |
# |   "66568"     |""         |"[66568] MG - BELO HORIZONTE - ASM INFORMÁTICA CARTUCHOS E TONER LTDA"                 |"[1] VENDAS"                                       |"28"         |"CT0041"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "62251"                 |"N"           |""             |  "2"      |  "CT0041 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda para"     |
# |   "66568"     |""         |"[66568] MG - BELO HORIZONTE - ASM INFORMÁTICA CARTUCHOS E TONER LTDA"                 |"[1] VENDAS"                                       |"28"         |"CT0041"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "9100700021 PPB"        |"N"           |""             |  "3"      |  "CT0041 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda para"     |
# |   "94728"     |""         |"[94728] MG - BELO HORIZONTE - INST.CULTURAL NEWTON PAIVA FERREIRA LTDA"               |"[1] VENDAS"                                       |"28"         |"CT0042"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BZ1200-BR PPB"         |"N"           |""             |  "1"      |  "CT0042 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda"          |
# |   "94728"     |""         |"[94728] MG - BELO HORIZONTE - INST.CULTURAL NEWTON PAIVA FERREIRA LTDA"               |"[1] VENDAS"                                       |"28"         |"CT0042"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BZ600PDVBI-BR"         |"N"           |""             |  "2"      |  "CT0042 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda"          |
# |   "94728"     |""         |"[94728] MG - BELO HORIZONTE - INST.CULTURAL NEWTON PAIVA FERREIRA LTDA"               |"[1] VENDAS"                                       |"28"         |"CT0043"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "9100700021 PPB"        |"N"           |""             |  "1"      |  "CT0043 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda"          |
# |   "94728"     |""         |"[94728] MG - BELO HORIZONTE - INST.CULTURAL NEWTON PAIVA FERREIRA LTDA"               |"[1] VENDAS"                                       |"28"         |"CT0043"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "9100700021 PPB"        |"N"           |""             |  "2"      |  "CT0043 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda"          |
# |   "94728"     |""         |"[94728] MG - BELO HORIZONTE - INST.CULTURAL NEWTON PAIVA FERREIRA LTDA"               |"[1] VENDAS"                                       |"28"         |"CT0043"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "SOL1000G4BI-BR"        |"N"           |""             |  "3"      |  "CT0043 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda"          |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A                |"[1] VENDAS"                                       |"28"         |"CT0046"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "PTH460K0A I"           |"N"           |""             |  "1"      |  "CT0046- Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda para uso"  |
# |   "62161"     |""         |"[62161] RJ - RESENDE - JOAO PAULO II PRODUTOS DE INFORMATICA LT"                      |"[1] VENDAS"                                       |"28"         |"CT0047"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "GA-H110M-S2V DDR4"     |"N"           |""             |  "1"      |  "CT0047-Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda para"       |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT0048"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "PTH460K0A TSC"         |"N"           |""             |  "1"      |  "CT0048 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda para"     |
# |   "140563"    |""         |"[140563] SP - SÃO PAULO - R. L. CAVALCANTI - ME"                                      |"[1] VENDAS"                                       |"28"         |"CT0049"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "PTH460K0A TSC"         |"N"           |""             |  "1"      |  "CT0049-Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda para uso e" |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[130] TRANSFERENCIA MERCADORIA PARA USO/CONSUMO"  |"600"        |"CT0051"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "CS710B I"              |"N"           |""             |  "1"      |  "CT0051 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 130-TRANSFERENCIA"         |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[130] TRANSFERENCIA MERCADORIA PARA USO/CONSUMO"  |"28"         |"CT0051-2"  |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "CS710B I"              |"N"           |""             |  "1"      |  "CT0051 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 130-TRANSFERENCIA"         |
# |   "258666"    |"49790"    |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[23] TRANSFERÊNCIA PARA FILIAL"                   |"600"        |"CT0052"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "PTH460K0A TSC"         |"N"           |""             |  "1"      |  "CT0052-Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 23-TRANSFERÊNCIA PARA"       |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0052-2"  |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "PTH460K0A TSC"         |"N"           |""             |  "1"      |  "CT0052-Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 23-TRANSFERÊNCIA PARA"       |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0053"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "PTH460K0A I"           |"N"           |""             |  "1"      |  "CT0053 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda para uso" |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0053-2"  |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "PTH460K0A I"           |"N"           |""             |  "1"      |  "CT0053 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 1-VENDAS e Venda para uso" |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[9] REMESSA CONTRA ORDEM DE TERC."                |"28"         |"CT0054"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I38100 I S"     |"N"           |""             |  "1"      |  "CT0054 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 9-VENDA CONTA A ORDEM"     |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[36] BONIFICAÇÃO"                                 |"600"        |"CT0055"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "PTH460K0A I"           |"N"           |""             |  "1"      |  "CT0055 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 36-BONIFICAÇÃO"            |
# |   "104003"    |""         |"[104003] ES - VITÓRIA - R2 TECNOLOGIA LTDA"                                           |"[7] DEVOLUÇÃO COMPRA		                        |"600"        |"CT0056"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0056 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 7 - DEVOLUÇÃO DE"          |
# |   "258685"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0057"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "P4MA00736702FGM"       |"N"           |""             |  "1"      |  "CT0057 - Gerar pedido de venda estabelecimento = 18 com Tipo de Operação = 1-VENDAS e Venda para uso" |
# |   "350796"    |""         |"[350796] RS - PORTO ALEGRE - INEEX ESPACO ESPORTIVO DE CONDICIONAMENTO FISICO L"      |"[1] VENDAS"                                       |"28"         |"CT0058"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "P4MA00736702FGM"       |"N"           |""             |  "1"      |  "CT0058 - Gerar pedido de venda estabelecimento = 18 com Tipo de Operação = 1-VENDAS e Venda para uso" |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0059"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "P4MA00736702FGM"       |"N"           |""             |  "1"      |  "CT0059 - Gerar pedido de venda estabelecimento = 18 com Tipo de Operação = 1-VENDAS e Venda para uso" |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT0059-2"  |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "P4MA00736702FGM"       |"N"           |""             |  "1"      |  "CT0059 - Gerar pedido de venda estabelecimento = 18 com Tipo de Operação = 1-VENDAS e Venda para uso" |
# |   "258685"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0060"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "P4MA00736702FGM"       |"N"           |""             |  "1"      |  "CT0060 - Gerar pedido de venda estabelecimento = 18 com Tipo de Operação = 1-VENDAS e Venda para"     |
# |   "174374"    |""         |"[174374] AM - MANAUS - J L CHAAR SIMAO"                                               |"[47] VENDA Z. FRANCA DE MANAUS - PIS/COFINS       |"28"         |"CT0061"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "CS710B I"              |"N"           |""             |  "1"      |  "CT0061 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 47-VENDA Z. FRANCA DE"     |
# |   "335461"    |""         |"[335461] ES - VITORIA - SERVICESB2B TECNOLOGIA LTDA"                                  |"[1] VENDAS"                                       |"28"         |"CT0062"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0062 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 47-VENDA Z. FRANCA DE"     |
# |   "346561"    |""         |"[335461] ES - VITORIA - SERVICESB2B TECNOLOGIA LTDA"                                  |"[47] VENDA Z. FRANCA DE MANAUS - PIS/COFINS"      |"28"         |"CT0062"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "CS710B I"              |"N"           |""             |  "1"      |  "CT0062 - Gerar pedido de venda estabelecimento = 16 com Tipo de Operação = 47-VENDA Z. FRANCA DE"     |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT0064"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0064 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 1-VENDAS e Venda para"     |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0064-2"  |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0064 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 1-VENDAS e Venda para"     |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[23] TRANSFERÊNCIA PARA FILIAL                    |"600"        |"CT0065"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "11BL0008BP"            |"N"           |""             |  "1"      |  "CT0065 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 23-TRANSFERÊNCIA PARA"     |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[64] SIMPLES REMESSA (COM IMPOSTOS)               |"28"         |"CT0066"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0066 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 64-SIMPLES REMESSA (COM"   |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT0067"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0067 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 1-VENDAS e Venda para uso" |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[58] TRANSFERENCIA IMOBILIZADO"                   |"28"         |"CT0068"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0068 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 129-TRANSFERENCIA ATIVO"   |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[58] TRANSFERENCIA IMOBILIZADO"                   |"28"         |"CT0069"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX8070110400 I"        |"N"           |""             |  "1"      |  "CT0069 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 129-TRANSFERENCIA ATIVO"   |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[130] TRANSFERENCIA MERCADORIA PARA USO/CONSUMO"  |"28"         |"CT0070"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "11BL0006BR"            |"N"           |""             |  "1"      |  "CT0070 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 130-TRANSFERENCIA"         |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[130] TRANSFERENCIA MERCADORIA PARA USO/CONSUMO"  |"28"         |"CT0070"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "TECLA00"               |"N"           |""             |  "2"      |  "CT0070 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 130-TRANSFERENCIA"         |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[130] TRANSFERENCIA MERCADORIA PARA USO/CONSUMO"  |"28"         |"CT0070"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "MOUSE00"               |"N"           |""             |  "3"      |  "CT0070 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 130-TRANSFERENCIA"         |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[36] BONIFICAÇÃO"                                 |"600"        |"CT0071"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0071-Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 36-BONIFICAÇÃO e Venda"      |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[127] BX STK PARA ATIVO IMOBILIZADO"              |"28"         |"CT0072"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80677I57400 I S"     |"N"           |""             |  "1"      |  "CT0072- Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 127-BX STK PARA ATIVO"      |
# |   "282073"    |""         |"[282073]  - SERRA - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"                  |"[7] DEVOLUÇÃO COMPRA"                             |"600"        |"CT0073"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80677I37100 I S"     |"N"           |""             |  "1"      |  "CT0073-Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 7-DEVOLUÇÃO COMPRA e"        |
# |   "248500"    |""         |"[248500] MG - BELO HORIZONTE - QUALIPIX TECNOLOGIA EM EQUIPAMENTOS AUDIOVISUAIS -"    |"[7] DEVOLUÇÃO COMPRA"                             |"600"        |"CT0074"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "MS550"                 |"N"           |""             |  "1"      |  "CT0074 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 7-DEVOLUÇÃO COMPRA e"      |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A                |"[23] TRANSFERÊNCIA PARA FILIAL"                   |"600"        |"CT0075"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0075 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 23-TRANSFERÊNCIA PARA"     |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[36] BONIFICAÇÃO"                                 |"600"        |"CT0076"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0076 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 36-BONIFICAÇÃO e Venda"    |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0076-2"  |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0076 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 36-BONIFICAÇÃO e Venda"    |
# |   "274173"    |"49790"    |"[274173] ES - SERRA - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"                |"[32] OUTRAS SAIDAS"                               |"600"        |"CT0077"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0077- Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 9-REMESSA CONTRA ORDEM"     |
# |   "258666"    |"49790"    |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[9] REMESSA CONTRA ORDEM DE TERC."                |"28"         |"CT0077"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0077- Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 9-REMESSA CONTRA ORDEM"     |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[9] REMESSA CONTRA ORDEM DE TERC."                |"28"         |"CT0078"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0078- Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 9-REMESSA CONTRA ORDEM"     |
# |   "274173"    |""         |"[274173] ES - SERRA - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"                |"[32] OUTRAS SAIDAS"25                             |"600"        |"CT0078"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0078- Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 9-REMESSA CONTRA ORDEM"     |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT0079"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80684I59400F I"      |"N"           |""             |  "1"      |  "CT0079- Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 1-VENDAS e Venda para"      |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[25] VENDAS ENTREGA FUTURA"                       |"28"         |"CT0080"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80677I57400 I S"     |"N"           |""             |  "1"      |  "CT0080 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 25-VENDAS ENTREGA"         |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[66] VENDA FATURAMENTO ANTECIPADO"                |"28"         |"CT0081"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80677I57400 I S"     |"N"           |""             |  "1"      |  "CT0081- Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 66-VENDA FATURAMENTO"       |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0082"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80677I57400 I S"     |"N"           |""             |  "1"      |  "CT0082 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 1-VENDAS e Venda para uso" |
# |   "174374"    |""         |"[174374] AM - MANAUS - J L CHAAR SIMAO"                                               |"[47] VENDA Z. FRANCA DE MANAUS - PIS/COFINS"      |"28"         |"CT0083"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "BX80677I57400 I S"     |"N"           |""             |  "1"      |  "CT0083- Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 47-VENDA Z. FRANCA DE"      |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[9] REMESSA CONTRA ORDEM DE TERC."                |"28"         |"CT0084"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80677I57400 I S"     |"N"           |""             |  "1"      |  "CT0084 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 9-REMESSA CONTRA ORDEM"    |
# |   "174374"    |""         |"[174374] AM - MANAUS - J L CHAAR SIMAO"                                               |"[47] VENDA Z. FRANCA DE MANAUS - PIS/COFINS"      |"28"         |"CT0085"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80677I57400 I S"     |"N"           |""             |  "1"      |  "CT0085 - Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 47-VENDA Z. FRANCA DE"     |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[128] BX STK PARA USO/CONSUMO"                    |"79"         |"CT0086"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"4.7"       |   "BX80677I57400 I S"     |"N"           |""             |  "1"      |  "CT0086 Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 128-BX STK PARA"             |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[50] SIMPLES REMESSA (SEM IMPOSTOS)"              |"28"         |"CT0087"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80677I57400 I S"     |"N"           |""             |  "1"      |  "CT0087-Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 50-SIMPLES REMESSA (SEM"     |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP                                                     |"[1] VENDAS"                                       |"873"        |"CT0088"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "Q6Y-00003 BRL"         |"N"           |""             |  "1"      |  "CT0088-Gerar pedido de venda estabelecimento = 22 com Tipo de Operação = 1-VENDAS e Venda para uso e" |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"252"        |"CT0089"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"6.2"       |   "Q5Y-00003 BRL"         |"N"           |""             |  "1"      |  "CT0089-Gerar pedido de venda estabelecimento = 22 com Tipo de Operação = 1-VENDAS e Venda para uso e" |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"16"         |"CT0090"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"3.2"       |   "79P-05729 BRL"         |"N"           |""             |  "1"      |  "CT0090-Gerar pedido de venda estabelecimento = 22 com Tipo de Operação = 1-VENDAS e Venda para"       |
# |   "250567"    |""         |"[250567] RJ - RIO DE JANEIRO - MAXGEN COMERCIO INDUSTRIAL IMPORTACAO E EXPORTACAO"    |"[7] DEVOLUÇÃO COMPRA                              |"600"        |"CT0091"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "MOUSE ZOWIE EC1-B"     |"N"           |""             |  "1"      |  "CT0091 - Gerar pedido de venda estabelecimento = 23 com Tipo de Operação = 7-DEVOLUÇÃO COMPRA e"      |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"28"         |"CT0092"    |"USO CONSUMO"       |    "CIF"  |"0"         |   "CT4G4DFS824A I"        |"N"           |""             |  "1"      |  "CT0092-Gerar pedido de venda estabelecimento = 23 com Tipo de Operação = 1-VENDAS e Venda para uso e" |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT0093"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "CT4G4DFS824A I"        |"N"           |""             |  "1"      |  "CT0093-Gerar pedido de venda estabelecimento = 23 com Tipo de Operação = 1-VENDAS e Venda para"       |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[23] TRANSFERÊNCIA PARA FILIAL                    |"600"        |"CT0094"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "CT4G4DFS824A I"        |"N"           |""             |  "1"      |  "CT0094-Gerar pedido de venda estabelecimento = 23 com Tipo de Operação = 23-TRANSFERÊNCIA PARA"       |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"16"         |"CT0106"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"3.2"       |   "BX80684I39100F I"      |"N"           |""             |  "1"      |  "CT0106-Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 1-VENDAS e Venda para"       |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"16"         |"CT0107"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "CT4G4DFS824A I"        |"N"           |""             |  "1       |  "CT0107-Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 1-VENDAS e Venda para"       |
# |   "49790"     |""         |"[49790] SP - BARUERI - SND DISTRIBUICAO DE PRODUTOS DE INFORMATICA S/A"               |"[1] VENDAS"                                       |"28"         |"CT0108"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "BX80677I37100 I S"     |"N"           |""             |  "1       |  "CT0108-Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 1-VENDAS e Venda para"       |
# |   "258666"    |""         |"[258666] SP - Barueri - SND-NC-SP"                                                    |"[1] VENDAS"                                       |"16"         |"CT0109"    |"COMERCIALIZAÇÃO"   |    "CIF"  |"0"         |   "XE501C13-AD2BR"        |"N"           |""             |  "1       |  "CT0109-Gerar pedido de venda estabelecimento = 21 com Tipo de Operação = 1-VENDAS e Venda para"       |
















































